# Generated by Django 5.0.2 on 2024-04-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Origin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "origin",
                "verbose_name_plural": "Origins",
                "db_table": "origins",
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_name", models.CharField(max_length=255)),
                ("word_description", models.TextField()),
                ("word_examples", models.TextField()),
                (
                    "word_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_word.category",
                    ),
                ),
                (
                    "word_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_word.origin",
                    ),
                ),
            ],
            options={
                "verbose_name": "word",
                "verbose_name_plural": "Words",
                "db_table": "words",
            },
        ),
    ]
